import type { Metadata } from 'next';
import './globals.scss';
import { Providers } from './Providers';
import { Fira_Mono } from 'next/font/google';

const inter = Fira_Mono({ subsets: ['cyrillic', 'latin'], weight: '400' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
