import type { Metadata } from 'next';
import './globals.scss';
import { Providers } from './Providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
